# Generated by Django 4.0.2 on 2022-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soil_mositure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mositure', models.FloatField()),
                ('time', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'soil mositure',
                'verbose_name_plural': 'soil mositure',
            },
        ),
    ]
