# Generated by Django 4.0.2 on 2022-10-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_reading', '0003_rename_soil_mositure_soil_moisture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Water',
            },
        ),
    ]
